name: 同步外刊到Obsidian

on:
  workflow_run:
    workflows: ["同步上游仓库"]
    types:
      - completed
  workflow_dispatch:

jobs:
  sync-to-r2:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          sparse-checkout: |
            01_economist
            02_new_yorker
            04_atlantic
            05_wired
          sparse-checkout-cone-mode: true

      - name: 安装AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: 配置R2凭证
        run: |
          mkdir -p ~/.aws
          cat > ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
          EOF

          cat > ~/.aws/config << EOF
          [default]
          region = auto
          output = json
          s3 =
            addressing_style = virtual
            endpoint_url = https://0c631cf1ad0f49201a8262eb0b4d5214.r2.cloudflarestorage.com
          EOF

          echo "AWS CLI配置："
          aws configure list

      - name: 列出目录内容
        run: |
          echo "经济学人目录：" && ls -la ./01_economist || echo "目录不存在"
          echo "纽约客目录：" && ls -la ./02_new_yorker || echo "目录不存在"
          echo "Atlantic目录：" && ls -la ./04_atlantic || echo "目录不存在"
          echo "Wired目录：" && ls -la ./05_wired || echo "目录不存在"

      - name: 查找最新的经济学人文件
        id: economist
        run: |
          if [ -d "./01_economist" ]; then
            LATEST_DIR=$(find ./01_economist -maxdepth 1 -type d -name "te_*" | sort -r | head -n 1)
            echo "latest_dir=$LATEST_DIR" >> $GITHUB_OUTPUT
            
            if [ -n "$LATEST_DIR" ]; then
              DIR_NAME=$(basename "$LATEST_DIR")
              echo "date=${DIR_NAME#te_}" >> $GITHUB_OUTPUT
              echo "找到经济学人目录: $LATEST_DIR"
            fi
          else
            echo "latest_dir=" >> $GITHUB_OUTPUT
          fi

      - name: 查找最新的纽约客文件
        id: newyorker
        run: |
          if [ -d "./02_new_yorker" ]; then
            LATEST_DIR=$(find ./02_new_yorker -maxdepth 1 -type d -mindepth 1 | sort -r | head -n 1)
            echo "latest_dir=$LATEST_DIR" >> $GITHUB_OUTPUT
            
            if [ -n "$LATEST_DIR" ]; then
              echo "date=$(basename "$LATEST_DIR")" >> $GITHUB_OUTPUT
              echo "找到纽约客目录: $LATEST_DIR"
            fi
          else
            echo "latest_dir=" >> $GITHUB_OUTPUT
          fi

      - name: 同步经济学人到R2
        if: steps.economist.outputs.latest_dir != ''
        run: |
          R2_ENDPOINT="https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com"
          
          for file in "${{ steps.economist.outputs.latest_dir }}"/*.pdf; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              s3_key="2.外刊/经济学人/${{ steps.economist.outputs.date }}/$filename"
              
              if aws s3api head-object \
                --bucket ${{ secrets.R2_BUCKET_NAME }} \
                --key "$s3_key" \
                --endpoint-url="$R2_ENDPOINT" 2>/dev/null; then
                echo "已存在: $s3_key"
              else
                echo "上传: $file"
                aws s3api put-object \
                  --bucket ${{ secrets.R2_BUCKET_NAME }} \
                  --key "$s3_key" \
                  --body "$file" \
                  --content-length $(stat -c%s "$file") \
                  --endpoint-url="$R2_ENDPOINT"
              fi
            fi
          done

      - name: 同步纽约客到R2
        if: steps.newyorker.outputs.latest_dir != ''
        run: |
          R2_ENDPOINT="https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com"
          
          for file in "${{ steps.newyorker.outputs.latest_dir }}"/*.pdf; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              s3_key="2.外刊/纽约客/${{ steps.newyorker.outputs.date }}/$filename"
              
              if aws s3api head-object \
                --bucket ${{ secrets.R2_BUCKET_NAME }} \
                --key "$s3_key" \
                --endpoint-url="$R2_ENDPOINT" 2>/dev/null; then
                echo "已存在: $s3_key"
              else
                echo "上传: $file"
                aws s3api put-object \
                  --bucket ${{ secrets.R2_BUCKET_NAME }} \
                  --key "$s3_key" \
                  --body "$file" \
                  --content-length $(stat -c%s "$file") \
                  --endpoint-url="$R2_ENDPOINT"
              fi
            fi
          done

      - name: 同步The Atlantic到R2
        run: |
          R2_ENDPOINT="https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com"
          
          if [ -d "./04_atlantic" ]; then
            LATEST_DIR=$(find ./04_atlantic -maxdepth 1 -type d -mindepth 1 | sort -r | head -n 1)
            if [ -n "$LATEST_DIR" ]; then
              DATE=$(basename "$LATEST_DIR")
              
              for file in "$LATEST_DIR"/*.pdf; do
                if [ -f "$file" ]; then
                  filename=$(basename "$file")
                  s3_key="2.外刊/大西洋月刊/$DATE/$filename"
                  
                  if aws s3api head-object \
                    --bucket ${{ secrets.R2_BUCKET_NAME }} \
                    --key "$s3_key" \
                    --endpoint-url="$R2_ENDPOINT" 2>/dev/null; then
                    echo "已存在: $s3_key"
                  else
                    echo "上传: $file"
                    aws s3api put-object \
                      --bucket ${{ secrets.R2_BUCKET_NAME }} \
                      --key "$s3_key" \
                      --body "$file" \
                      --content-length $(stat -c%s "$file") \
                      --endpoint-url="$R2_ENDPOINT"
                  fi
                fi
              done
            fi
          fi

      - name: 同步Wired到R2
        run: |
          R2_ENDPOINT="https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com"
          
          if [ -d "./05_wired" ]; then
            LATEST_DIR=$(find ./05_wired -maxdepth 1 -type d -mindepth 1 | sort -r | head -n 1)
            if [ -n "$LATEST_DIR" ]; then
              DATE=$(basename "$LATEST_DIR")
              
              for file in "$LATEST_DIR"/*.pdf; do
                if [ -f "$file" ]; then
                  filename=$(basename "$file")
                  s3_key="2.外刊/连线杂志/$DATE/$filename"
                  
                  if aws s3api head-object \
                    --bucket ${{ secrets.R2_BUCKET_NAME }} \
                    --key "$s3_key" \
                    --endpoint-url="$R2_ENDPOINT" 2>/dev/null; then
                    echo "已存在: $s3_key"
                  else
                    echo "上传: $file"
                    aws s3api put-object \
                      --bucket ${{ secrets.R2_BUCKET_NAME }} \
                      --key "$s3_key" \
                      --body "$file" \
                      --content-length $(stat -c%s "$file") \
                      --endpoint-url="$R2_ENDPOINT"
                  fi
                fi
              done
            fi
          fi
