name: 同步外刊到Cloudflare R2

on:
  workflow_run:
    workflows: ["同步上游仓库"]
    types:
      - completed
  workflow_dispatch:

jobs:
  sync-to-r2:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          sparse-checkout: |
            01_economist
            02_new_yorker
            04_atlantic
            05_wired
          sparse-checkout-cone-mode: true

      - name: 安装AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2.22.35

      - name: 配置AWS凭证
        run: |
          mkdir -p ~/.aws
          cat > ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
          EOF
          
          cat > ~/.aws/config << EOF
          [default]
          region = auto
          output = json
          EOF
          aws configure set s3.multipart_threshold 999GB

      # 移除原有的"查找最新文件"步骤

      - name: 同步经济学人到R2
        run: |
          if [ -d "./01_economist" ]; then
            find "./01_economist" -type d -name "te_*" | while read dir; do
              dir_name=$(basename "$dir")
              economist_date=$(echo "$dir_name" | sed 's/te_//')
              echo "正在处理目录: $dir"
              
              for file in "$dir"/*.pdf; do
                if [ -f "$file" ]; then
                  filename=$(basename "$file")
                  s3_key="2.外刊/经济学人/$economist_date/$filename"
                  
                  if aws s3api head-object --bucket ${{ secrets.R2_BUCKET_NAME }} \
                     --key "$s3_key" \
                     --endpoint-url "https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com" \
                     2>/dev/null; then
                    echo "文件已存在，跳过上传: $s3_key"
                  else
                    echo "正在上传: $filename"
                    aws s3 cp "$file" "s3://${{ secrets.R2_BUCKET_NAME }}/$s3_key" \
                      --endpoint-url "https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com" \
                      --no-progress \
                      --checksum-algorithm CRC32
                  fi
                fi
              done
            done
          else
            echo "经济学人目录不存在"
          fi

      - name: 同步纽约客到R2
        run: |
          if [ -d "./02_new_yorker" ]; then
            find "./02_new_yorker" -type d -mindepth 1 -not -path "*/\.*" | while read dir; do
              dir_name=$(basename "$dir")
              echo "正在处理目录: $dir"
              
              for file in "$dir"/*.pdf; do
                if [ -f "$file" ]; then
                  filename=$(basename "$file")
                  s3_key="2.外刊/纽约客/$dir_name/$filename"
                  
                  if aws s3api head-object --bucket ${{ secrets.R2_BUCKET_NAME }} \
                     --key "$s3_key" \
                     --endpoint-url "https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com" \
                     2>/dev/null; then
                    echo "文件已存在，跳过上传: $s3_key"
                  else
                    echo "正在上传: $filename"
                    aws s3 cp "$file" "s3://${{ secrets.R2_BUCKET_NAME }}/$s3_key" \
                      --endpoint-url "https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com" \
                      --no-progress \
                      --checksum-algorithm CRC32
                  fi
                fi
              done
            done
          else
            echo "纽约客目录不存在"
          fi

      - name: 同步The Atlantic到R2
        run: |
          if [ -d "./04_atlantic" ]; then
            find "./04_atlantic" -type d -mindepth 1 -not -path "*/\.*" | while read dir; do
              dir_name=$(basename "$dir")
              echo "正在处理目录: $dir"
              
              for file in "$dir"/*.pdf; do
                if [ -f "$file" ]; then
                  filename=$(basename "$file")
                  s3_key="2.外刊/大西洋月刊/$dir_name/$filename"
                  
                  if aws s3api head-object --bucket ${{ secrets.R2_BUCKET_NAME }} \
                     --key "$s3_key" \
                     --endpoint-url "https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com" \
                     2>/dev/null; then
                    echo "文件已存在，跳过上传: $s3_key"
                  else
                    echo "正在上传: $filename"
                    aws s3 cp "$file" "s3://${{ secrets.R2_BUCKET_NAME }}/$s3_key" \
                      --endpoint-url "https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com" \
                      --no-progress \
                      --checksum-algorithm CRC32
                  fi
                fi
              done
            done
          else
            echo "Atlantic目录不存在"
          fi

      - name: 同步Wired到R2
        run: |
          if [ -d "./05_wired" ]; then
            find "./05_wired" -type d -mindepth 1 -not -path "*/\.*" | while read dir; do
              dir_name=$(basename "$dir")
              echo "正在处理目录: $dir"
              
              for file in "$dir"/*.pdf; do
                if [ -f "$file" ]; then
                  filename=$(basename "$file")
                  s3_key="2.外刊/连线杂志/$dir_name/$filename"
                  
                  if aws s3api head-object --bucket ${{ secrets.R2_BUCKET_NAME }} \
                     --key "$s3_key" \
                     --endpoint-url "https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com" \
                     2>/dev/null; then
                    echo "文件已存在，跳过上传: $s3_key"
                  else
                    echo "正在上传: $filename"
                    aws s3 cp "$file" "s3://${{ secrets.R2_BUCKET_NAME }}/$s3_key" \
                      --endpoint-url "https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com" \
                      --no-progress \
                      --checksum-algorithm CRC32
                  fi
                fi
              done
            done
          else
            echo "Wired目录不存在"
          fi
